flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- legion-discovery-client-0.3.2.0
- load-balancing-1.0.1.1
- om-fork-0.2.0.0
- om-json-0.2.3.0
- om-lift-0.1.0.0
- om-logging-0.2.0.2
- om-powerstate-1.1.0.0
- om-show-0.1.0.1
- om-socket-0.6.0.0
resolver: lts-11.6
