flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- base58-bytestring-0.1.0
- cached-io-1.1.0.0
- load-balancing-1.0.1.2
- om-account-types-5.2.4.0
- om-base58-0.1.0.0
- om-compute-types-0.3.3.0
- om-deploy-types-1.3.0.0
- om-discovery-client-0.1.1.0
- om-fork-0.4.0.0
- om-gce-metadata-0.1.4.0
- om-hash-0.1.0.0
- om-json-0.2.4.0
- om-lift-0.1.0.1
- om-logging-0.2.0.3
- om-powerstate-3.1.0.0
- om-show-0.1.0.2
- om-socket-0.7.0.0
resolver: lts-12.17
