flags: {}
extra-package-dbs: []
packages:
  - .
extra-deps:
  - http://localhost:4563/package/crdt-event-fold-1.7.1.0.tar.gz
  - http://localhost:4563/package/om-fork-0.7.1.3.tar.gz
  - http://localhost:4563/package/om-kubernetes-2.3.1.1.tar.gz
  - http://localhost:4563/package/om-logging-1.1.0.1.tar.gz
  - http://localhost:4563/package/om-show-0.1.2.1.tar.gz
  - http://localhost:4563/package/om-socket-0.9.0.2.tar.gz
  - http://localhost:4563/package/om-socket-server-0.1.0.3.tar.gz
  - http://localhost:4563/package/om-http-0.2.0.2.tar.gz
  - mustache-2.4.1
resolver: lts-19.18
