flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- base58-bytestring-0.1.0
- cached-io-1.1.0.0
- load-balancing-1.0.1.3
- om-account-types-5.3.1.2
- om-base58-0.1.0.1
- om-compute-types-0.3.3.1
- om-deploy-types-1.3.0.3
- om-discovery-client-0.1.1.1
- om-fork-0.5.0.1
- om-gce-metadata-0.1.4.1
- om-hash-0.3.0.1
- om-json-0.2.4.1
- om-lift-0.1.0.2
- om-logging-0.2.0.4
- om-powerstate-4.0.0.1
- om-show-0.1.0.3
- om-socket-0.7.0.1
- text-show-3.7.5
resolver: lts-13.0
